# Generated by Django 4.2.4 on 2023-08-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='documents'),
        ),
    ]
