# Generated by Django 4.2.4 on 2023-08-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_course_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='subtitle',
            field=models.CharField(default='sample.txt', max_length=100),
        ),
    ]
