# Generated by Django 4.2.4 on 2023-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courses_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default='35000', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subtitle',
            field=models.CharField(default='6 months', max_length=100),
        ),
    ]
