# Generated by Django 4.2.4 on 2023-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_courses_price_alter_courses_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default='35000'),
        ),
    ]
